package com.yjk.biz.domain;

public class Appl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.appl_cde
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    private String applCde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appl.name
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.appl_cde
     *
     * @return the value of appl.appl_cde
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    public String getApplCde() {
        return applCde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.appl_cde
     *
     * @param applCde the value for appl.appl_cde
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    public void setApplCde(String applCde) {
        this.applCde = applCde == null ? null : applCde.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appl.name
     *
     * @return the value of appl.name
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appl.name
     *
     * @param name the value for appl.name
     *
     * @mbg.generated Thu Aug 22 11:14:47 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}